import { CheckCircle2, Circle, GitBranch } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import type { PpwrRoleAssessment, PpwrRoleScenario } from "@/lib/ppwr-role-types";

function hasManufacturerTrigger(scenario: PpwrRoleScenario) {
  return (
    scenario.manufacturesPackaging ||
    scenario.manufacturesPackagedProduct ||
    scenario.sellsUnderOwnBrand ||
    scenario.privateLabelsOrRebrands ||
    scenario.modifiesPackaging
  );
}

export function RoleDecisionTree({
  scenario,
  assessment
}: {
  scenario: PpwrRoleScenario;
  assessment: PpwrRoleAssessment;
}) {
  const nodes = [
    {
      title: "EU market availability",
      triggered: !assessment.noEuPlacingOnMarketRole,
      detail: assessment.noEuPlacingOnMarketRole
        ? "Export-only path selected."
        : "Packaging or packaged products may be placed or made available in the EU."
    },
    {
      title: "Technical conformity role",
      triggered: hasManufacturerTrigger(scenario) || assessment.importerResponsibility,
      detail: assessment.technicalConformityRole.length
        ? assessment.technicalConformityRole.join(", ")
        : "No technical conformity owner assigned by this demo logic."
    },
    {
      title: "EPR producer trigger",
      triggered: assessment.eprProducer,
      detail: assessment.eprProducer
        ? `${assessment.eprResponsibleParty} Member State(s): ${assessment.eprMemberStates.join(", ") || "to be confirmed"}.`
        : "No first making-available, direct-to-end-user or unpacking trigger identified."
    },
    {
      title: "Supplier data path",
      triggered: assessment.supplierDataObligation,
      detail: assessment.supplierDataObligation
        ? "Supplier evidence and material data should be collected."
        : "No supplier-only evidence role assigned."
    },
    {
      title: "Gatekeeper relevance",
      triggered: assessment.marketplaceVerificationRelevant || assessment.fulfilmentVerificationRelevant,
      detail: assessment.marketplaceVerificationRelevant || assessment.fulfilmentVerificationRelevant
        ? "Marketplace or fulfilment verification relevance is present; producer accuracy remains with the producer."
        : "No marketplace or fulfilment gatekeeper relevance selected."
    },
    {
      title: "Legal review checks",
      triggered: assessment.reviewFlags.length > 0,
      detail: assessment.reviewFlags.length
        ? assessment.reviewFlags.join(" ")
        : "No extra review flags generated by the demo logic."
    }
  ];

  return (
    <div className="rounded-lg border bg-white p-4">
      <div className="mb-3 flex items-center gap-2">
        <GitBranch className="h-4 w-4 text-blue-600" aria-hidden="true" />
        <h3 className="text-sm font-semibold text-slate-900">Decision tree</h3>
      </div>
      <div className="space-y-3">
        {nodes.map((node) => (
          <div key={node.title} className="grid grid-cols-[1.25rem_minmax(0,1fr)] gap-3">
            <div className="pt-1">
              {node.triggered ? (
                <CheckCircle2 className="h-4 w-4 text-emerald-600" aria-hidden="true" />
              ) : (
                <Circle className="h-4 w-4 text-slate-300" aria-hidden="true" />
              )}
            </div>
            <div className="min-w-0 border-b pb-3 last:border-b-0 last:pb-0">
              <div className="flex flex-wrap items-center gap-2">
                <p className="text-sm font-medium text-slate-900">{node.title}</p>
                <Badge variant={node.triggered ? "success" : "secondary"}>
                  {node.triggered ? "Triggered" : "Not triggered"}
                </Badge>
              </div>
              <p className="mt-1 text-xs leading-5 text-muted-foreground">{node.detail}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
